CREATE TABLE donations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    streamer_id VARCHAR(64) NOT NULL,
    sender_name VARCHAR(120) NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    currency VARCHAR(16) NOT NULL,
    message_text VARCHAR(1000) NOT NULL,
    voice_profile VARCHAR(64),
    tts_status VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE overlay_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donation_id BIGINT NOT NULL,
    streamer_id VARCHAR(64) NOT NULL,
    sender_name VARCHAR(120) NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    currency VARCHAR(16) NOT NULL,
    message_text VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_donations_streamer_created_at ON donations(streamer_id, created_at DESC);
CREATE INDEX idx_overlay_events_streamer_id_id ON overlay_events(streamer_id, id);
